// exchanges
export const USER_EXCHANGE = 'USER_EXCHANGE';
export const PROCESS_EXCHANGE = 'PROCESS_EXCHANGE';
export const OFFER_EXCHANGE = 'OFFER_EXCHANGE';
export const EVENT_EXCHANGE = 'EVENT_EXCHANGE';

// messages
export const USER_CREATED = 'USER_CREATED';
export const PROCESS_CREATED = 'PROCESS_CREATED';
export const PROCESS_PUBLISHED = 'PROCESS_PUBLISHED';
export const PROCESS_FINISHED = 'PROCESS_FINISHED';
export const OFFER_CREATED = 'OFFER_CREATED';
export const OFFER_ACCEPTED = 'OFFER_ACCEPTED';
export const OFFER_COMPLETED = 'OFFER_COMPLETED';
export const EVENT_CREATED = 'EVENT_CREATED';
export const EVENT_RECEIVED = 'EVENT_RECEIVED';

export const SERVICE_NAME = 'offers-svc';
